apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: NodePort
  ports:
  - port: 80 # The port that *this* service should serve on
    targetPort: 3000 # The container port
    protocol: TCP
  selector:
    app: kzonov-node-app
  type: LoadBalancer
