apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kzonov-node-app
  template:
    metadata:
      labels:
        app: kzonov-node-app
    spec:
      containers:
      - name: kzonov-node-app
        image: eu.gcr.io/babbel-sandbox/kzonov-node-app:latest
        ports:
        - containerPort: 3000
